### PR TITLE
keep script directives at top of file, fixes #185

### LINKED ISSUE #185: The sorter will incorrectly move the "use client" / "use strict" directive (Next 13), even if a prettier-ignore flag is set.
**Your Environment**
 * **Prettier version**: 2.7.1
 * **node version** 16.17.0:
 * **package manager**: yarn
 * **IDE**: VScode
 * **Plugin version**: 3.4.0

**Describe the bug**

Consider the following code:

```typescript
"use client";

import { useState } from "react";

export default function Test() {
	return <p>Test</p>;
}
```

On format, the «prettier-plugin-sort-imports», will move the `"use client";` directive below the imports, prettier will then wrap it in parenthesis since it's not at the top of file. This breaks client components in Next 13. The same happens when using the `use strict;` directive.

Adding «// prettier-ignore» above the `"use client";` directive does nothing. This part is probably related to #112.

**To Reproduce**

Use the code snippet above and run `prettier --write .`

**Expected behavior**

The `"use client";` directive should be left at the top of the file.

### PR DESCRIPTION
**Pull request by broofa**
This [hopefully] fixes #185 by extracting `Directive` nodes before processing the AST, and then re-injecting them as part of the `file()` generation used to create the import section of the script... which should preserve them at top-of-file.

Includes a new test case.  Compiles cleanly, all tests pass.

### CODE REVIEW

File: tests/ImportsNotSeparated/imports-with-directives.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+'use strict';
```
Comment (oliveiraantoniocc) [inline tests/ImportsNotSeparated/imports-with-directives.ts:1]: I guess having two directives will never exactly happen, I tested locally and worked with just one too.
If there's a comment in front of it, the comment will end up being moved to a new line above the directive, for RSC most probably this will be incompatible, so no comments explaining why "use client"; 😅

**Review by oliveiraantoniocc — APPROVED** [review]
If there's a comment in front of it, the comment will end up being moved to a new line above the directive, for RSC most probably this will be incompatible, so no comments explaining why `"use client"; // some explanation about directive will break RSC`.

This is certainly not critical, an solution would be keeping comments in front for directives.

File: tests/ImportsNotSeparated/imports-with-directives.ts (hunk 1 above)
Comment (oliveiraantoniocc) [reply tests/ImportsNotSeparated/imports-with-directives.ts:1]: Looking good. Well done!
image

**Comment by oliveiraantoniocc** [comment]
@ayusharma could you please approve this?

**Comment by broofa** [comment]
@ayusharma Thoughts?

I, and I suspect others here, would very much like to get this merged and published ASAP, as I don't believe there's a viable workaround for this issue other than to disable this plugin.

File: src/preprocessors/preprocessor.ts [hunk 2]
```diff
@@ -26,6 +26,16 @@ export function preprocessor(code: string, options: PrettierOptions) {
...
+    const directives: Directive[] = [];
+    traverse(ast, {
+        Directive({ node }) {
+            directives.push(node);
+
+            // Trailing comments probably shouldn't be attached to the directive
+            node.trailingComments = null;
+        },
+    });
+
```
Comment (ayusharma) [inline src/preprocessors/preprocessor.ts:38]: Can this **traverse** block not be moved into the **traverse** block ( along side with `ImportDeclaration` ) below ?

Comment (broofa) [reply src/preprocessors/preprocessor.ts]: Good catch. Fixed.

**Comment by tzii** [comment]
any update on this pull request?

File: src/utils/__tests__/get-code-from-ast.spec.ts [hunk 3]
```diff
@@ -22,7 +22,7 @@ import a from 'a';
         importOrderGroupNamespaceSpecifiers: false,
         importOrderSortSpecifiers: false,
     });
-    const formatted = getCodeFromAst(sortedNodes, code, null);
```
Comment (byara) [inline src/utils/__tests__/get-code-from-ast.spec.ts:25]: Is it possible to have one more test case with directives?

File: tests/ImportsNotSeparated/__snapshots__/ppsi.spec.js.snap [hunk 4]
```diff
@@ -151,6 +151,23 @@ function add(a: number, b: number) {
 
 `;
 
+exports[`imports-with-directives.ts - typescript-verify: imports-with-directives.ts 1`] = `
```
Comment (byara) [inline tests/ImportsNotSeparated/__snapshots__/ppsi.spec.js.snap:154]: It would b nice to have another test case for separated imports.

**Review by byara — COMMENTED** [review]
Great work @broofa 👏 
The PR looks good 👍 Would it be possible to add those two unit-test cases I mentioned?
If so I think we can merge it soon. What do you think @ayusharma?

File: tests/ImportsNotSeparated/__snapshots__/ppsi.spec.js.snap (hunk 4 above)
Comment (broofa) [reply tests/ImportsNotSeparated/__snapshots__/ppsi.spec.js.snap:154]: done.

File: src/utils/__tests__/get-code-from-ast.spec.ts (hunk 3 above)
Comment (broofa) [reply src/utils/__tests__/get-code-from-ast.spec.ts:25]: Done.

**Review by byara — APPROVED** [review]
LGTM 🚀
Thank you for your contribution!

**Comment by broofa** [comment]
@byara: Just pinging you to note my last change that refactors the `traverse()` logic that I'd copy/pasta'd from `preprocessor` into the `get-code-from-ast` test into it's own module/method. (i.e. so it's no longer copy/pasted.)

**Review by byara — APPROVED** [review]

**Review by ayusharma — APPROVED** [review]
Thank you for the changes ❤️. Looks good to me

**Comment by ayusharma** [comment]
@byara could you please release this?

**Comment by transitive-bullshit** [comment]
Amazing job @broofa 🙏 

As a workaround until this is released, you can use:

```
pnpm add @trivago/prettier-plugin-sort-imports@npm:@fisch0920/prettier-plugin-sort-imports
```

(or the equivalent for your package manager)

This just takes @broofa's fork and publishes it to npm.

**Comment by byara** [comment]
Released in [v4.0.0](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.0.0)

**Comment by simon-dk** [comment]
> Released in [v4.0.0](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.0.0)

Wow, that was fast! Much appreciated, and good job @broofa 👍

**Comment by ayusharma** [comment]
Released in [v4.1.0](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.1.0). I appreciate your patience. ❤️

**Comment by Keshavdulal** [comment]
Is this the default behaviour? @broofa 
I couldn't find anything on docs for Directives.

How do we achieve this? 
I am on `4.1.1` and trying to add "use client" directive on a nextjs project, but it keeps going down below imports as

`;('use client')`

This is my .prettierrc
```
{
  "singleQuote": true,
  "jsxSingleQuote": true,
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "printWidth": 100,
  "useTabs": false,
  "tabWidth": 2,
  "semi": false,
  "trailingComma": "es5",
  "jsxBracketSameLine": true,
  "endOfLine": "auto",
  "quoteProps": "as-needed",
  "importOrder": ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}
```

Thanks.

**Comment by cglacet** [comment]
@Keshavdulal Same issue here.

With the following dependencies:

```json
{
  "devDependencies": {
    "eslint": "^8.5",
    "prettier": "^3",
    "@trivago/prettier-plugin-sort-imports": "~4.2.0",
    "turbo": "^1.4.2",
    "typescript": "^5.2.2"
  },
}
```

**Comment by askjervold** [comment]
I get the same as @cglacet with version `4.3.0`. I ended up switching to use [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort) to handle this
